version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: ../api_yamdb
    restart: always
    volumes:
      - static_value:/api_yamdb/static/
    depends_on:
      - db
    env_file:
      - ./.env
  web-prepare:
    build: ../api_yamdb
    volumes:
      - static_value:/app/static/
    env_file:
      - ./.env
    command:
     - pre-run
  web-migrate:
    build: ../api_yamdb
    depends_on:
      - db
    env_file:
      - ./.env
    command:
      - migrate
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/:ro
    depends_on:
      - web

volumes:
  static_value:
